### PR TITLE
Fix openURLWithSafariViewController completion handler

### PR DESCRIPTION
**Pull request by turbulem**
In case when app was folded when permission alert is shown completion will never be called. For this case store completion and call it after application become active when folding was not expected

Changes affect only iOS11 logic in FBSDKApplicationDelegate class.

- [x] sign contributor license agreement: https://developers.facebook.com/opensource/cla
- [x] submit against our `:dev` branch, not `master`.
- [x] describe the change (for example, what happens before the change, and after the change)

### CODE REVIEW

**Comment by filwag** [comment]
@mcohnen could you please have a look at this?

**Comment by codytwinton** [comment]
@turbulem - This pull request looks good, but I'm unable to rebase and merge with this error:

```
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.
```

Can you rebase the dev branch onto your fork and push? If so, we'll review and get this merged.

**Comment by turbulem** [comment]
@codytwinton PR is ready. I did some checks in my app and everything seems to be ok. Looking forward for your response and review notes.

**Comment by codytwinton** [comment]
Hey @turbulem, we had an issue with the latest iOS SDK release where PRs were accidentally reverted on release. I'm doing some internal investigation to resolve this issue.

**Comment by turbulem** [comment]
@codytwinton Thank you for the update. Please, let me know if I need to resubmit it.

**Comment by codytwinton** [comment]
@turbulem - Thanks, it probably will need a new submission, but I'm still in process of resolving some stuff on my end. Stay tuned.

**Comment by codytwinton** [comment]
@turbulem - Ok, so sorry. We've got syncing back up and running. Do you mind re-submitting this PR?

**Pull request merged**
