### PR TITLE
LICENSE REFERENCE

### PR DESCRIPTION
**Pull request by Basarqari**

### CODE REVIEW

**Comment by chrisp-fb** [comment]
Hi, what's the motivation behind this change?

**Comment by Basarqari** [comment]
@facebook-github-bot I have registered for the contributor License Community and successfully received confirmation.

**Comment by Basarqari** [comment]
@chrisp-fb I am basically a Student and I wanted to join the community of Facebook as a contributor.I though that people could easily look for the license on the Readme so that they get easy to fetch it out rather than looking into the whole repository.I am very much glad to enter this community actually

**Comment by chrisp-fb** [comment]
I see. Well, the LICENSE file is comprehensive and I'd prefer to keep it all in one place (for example, it would be problematic if we update some language there and forget to do it to the README). That said, I'm glad you're interested in the community and hope you can find some other areas to contribute to. Thanks!

**Pull request closed without merging**
