### PR TITLE
correct condition for debug

### PR DESCRIPTION
**Pull request by thandang**
Thanks for proposing a pull request!

To help us review the request, please complete the following:

- [ ] sign [contributor license agreement](https://code.facebook.com/cla)
- [ ] I've ensured that all existing tests pass and added tests (when/where necessary)
- [ ] I've updated the documentation (when/where necessary) and [Changelog](CHANGELOG.md) (when/where necessary)
- [ ] I've added the proper label to this pull request (e.g. `bug` for bug fixes)

## Pull Request Details

It seems inconsistent change for _printedUpdateMessage 

## Test Plan

Perform xcodebuild with and without DEBUG works properly

### CODE REVIEW

**Review by andikaleonardo — APPROVED** [review]

**Review by LAI88888 — APPROVED** [review]

**Comment by jawwad** [comment]
Hi @thandang - Could you include a bit more detail about what difference this change makes and if you were running into any issues or that its just more proper to use #if instead of #ifdef. It would also help to add a brief explain of why (i.e. something like #ifdef would be incorrect if DEBUG was set to 0 although that would never be the case). Also in doing a grep for this I see 2 additional cases of "#ifdef DEBUG". Could you update those issues as well. Once you are done could you also rebase with master? Thanks!

**Review by jne0 — APPROVED** [review]

**Comment by jne0** [comment]
- [ ]

**Review by jne0 — APPROVED** [review]

**Comment by thandang** [comment]
> Hi @thandang - Could you include a bit more detail about what difference this change makes and if you were running into any issues or that its just more proper to use #if instead of #ifdef. It would also help to add a brief explain of why (i.e. something like #ifdef would be incorrect if DEBUG was set to 0 although that would never be the case). Also in doing a grep for this I see 2 additional cases of "#ifdef DEBUG". Could you update those issues as well. Once you are done could you also rebase with master? Thanks!

This is when I perform a xcodebuild command where in macro (GCC_PREPROCESSOR_DEFINITIONS) I put DEBUG=0 as debug is being used for environment. 
In this case case, it cause error for compiler as DEBUG has not be defined (=1 is expected)

**Comment by jawwad** [comment]
> This is when I perform a xcodebuild command where in macro (GCC_PREPROCESSOR_DEFINITIONS) I put DEBUG=0 as debug is being used for environment.
> In this case case, it cause error for compiler as DEBUG has not be defined (=1 is expected)
Hi @thandang - Could you incorporate this additional detail into the title and description of the actual pull request since that is the message that will be used for the commit. 

Also in doing a grep for this I see 2 additional cases of "#ifdef DEBUG". Could you update those issues as well. Once you are done could you also rebase with master? Thanks!

**Comment by jawwad** [comment]
@thandang - I haven't heard back from you and I want to close out this pull request so I'm going to import this and make the changes that I had requested on my end.

**Pull request closed without merging**
