### PR TITLE
Configure triage labels

### PR DESCRIPTION
**Pull request by xilosada**
Thanks for proposing a pull request!

To help us review the request, please complete the following:

- [x ] sign [contributor license agreement](https://code.facebook.com/cla)
- [ x] I've ensured that all existing tests pass and added tests (when/where necessary)
- [ x] I've updated the documentation (when/where necessary) and [Changelog](CHANGELOG.md) (when/where necessary)
- [x ] I've added the proper label to this pull request (e.g. `bug` for bug fixes)

## Pull Request Details

Enable 'needs-attention' github action. This action uses the labels 'needs-triage' and 'needs-feedback' to indicate the state of the issue. 'needs-feedback' is used when more information is required to start the resolution. 'needs-triage' indicates that a repo administrator has to triage the issue. This pull request also prevents stale action to close issues tagged with 'needs-triage' and 'acknowledged' labels.

### CODE REVIEW

**Comment by cavaer** [comment]
> Thanks for proposing a pull request!
> 
> To help us review the request, please complete the following:
> 
> * [x ] sign [contributor license agreement](https://code.facebook.com/cla)
> * [ x] I've ensured that all existing tests pass and added tests (when/where necessary)
> * [ x] I've updated the documentation (when/where necessary) and [Changelog](CHANGELOG.md) (when/where necessary)
> * [x ] I've added the proper label to this pull request (e.g. `bug` for bug fixes)
> 
> ## Pull Request Details
> Enable 'needs-attention' github action. This action uses the labels 'needs-triage' and 'needs-feedback' to indicate the state of the issue. 'needs-feedback' is used when more information is required to start the resolution. 'needs-triage' indicates that a repo administrator has to triage the issue. This pull request also prevents stale action to close issues tagged with 'needs-triage' and 'acknowledged' labels.

**Review by cavaer — COMMENTED** [review]
https://github.com/facebook/facebook-ios-sdk.git

**Comment by hadesragnarokclassic** [comment]
https://github.com/facebook/facebook-ios-sdk

**Comment by AegisRoClassic** [comment]
> Thanks for proposing a pull request!
> 
> To help us review the request, please complete the following:
> 
> * [x ] sign [contributor license agreement](https://code.facebook.com/cla)
> * [ x] I've ensured that all existing tests pass and added tests (when/where necessary)
> * [ x] I've updated the documentation (when/where necessary) and [Changelog](CHANGELOG.md) (when/where necessary)
> * [x ] I've added the proper label to this pull request (e.g. `bug` for bug fixes)
> 
> ## Pull Request Details
> Enable 'needs-attention' github action. This action uses the labels 'needs-triage' and 'needs-feedback' to indicate the state of the issue. 'needs-feedback' is used when more information is required to start the resolution. 'needs-triage' indicates that a repo administrator has to triage the issue. This pull request also prevents stale action to close issues tagged with 'needs-triage' and 'acknowledged' labels.

**Pull request closed without merging**
