### PR TITLE
fix log event login message

### PR DESCRIPTION
**Pull request by elvi117**
Thanks for proposing a pull request.

To help us review the request, please complete the following:
- [x] sign contributor license agreement: https://developers.facebook.com/opensource/cla
- [x] submit against our `:dev` branch, not `master`.
- [x] describe the change (for example, what happens before the change, and after the change)

### CODE REVIEW

**Comment by elvi117** [comment]
Module LoginKit doesn't work on "FBSDKAppEventNameFBSessionFASLoginDialogResult", Xcode recommended to change it to 'FBSDKAppEventNameFBDialogsNativeLoginDialogEnd' and now I can compile all SDK.

**Comment by codytwinton** [comment]
It appears that someone who has made a commit on this pull request has yet to sign the Contributor License Agreement. If that can be taken care of, we can get this pull request reviewed and merged!

**Comment by elvi117** [comment]
@codytwinton Hello, many thanks for information, I have just signed the CLA

**Comment by codytwinton** [comment]
Thanks for the contribution!

**Pull request merged**
