### PR TITLE
[Proj] Xcode 8.3 Compatibility

### PR DESCRIPTION
**Pull request by adomanico**
Xcode 8.3 requires that module map files have unique names. This is preventing compilation of the Facebook SDKs on Xcode 8.3

This simply gives the module map files of each framework unique names and allows all frameworks to be compiled by Xcode 8.3

To help us review the request, please complete the following:
- [X] sign contributor license agreement: https://developers.facebook.com/opensource/cla
- [X] submit against our `:dev` branch, not `master`.
- [X] describe the change (for example, what happens before the change, and after the change)

### CODE REVIEW

**Comment by adomanico** [comment]
@mcohnen Can we get this expediting into a release? XCode 8.3 is live to the public at this time

**Comment by adomanico** [comment]
cc @dzhuowen

**Comment by adomanico** [comment]
cc @chrisp-fb

**Comment by adomanico** [comment]
If anyone knows who is in charge of this repo and are active contributors please feel free to mention them

**Comment by Steven0351** [comment]
Not sure if this helps, but I was able to get my code to compile by removing the SDK from my podfile, ran pod install, re-added it to my podfile and ran pod-install again and it compiles fine.

**Comment by Andr3y-** [comment]
@nlutsenko

**Comment by Alak** [comment]
any news ?

**Comment by mcrollin** [comment]
Any ETA?

**Comment by Infinity-James** [comment]
Can you just merge this now? It's ridiculous.

**Comment by naluhh** [comment]
please

**Comment by latargere** [comment]
please update it !

**Comment by nicolasfallourd** [comment]
please 🙏

**Comment by muukii** [comment]
👀

**Comment by plailleur** [comment]
Please 🙂

**Comment by kentokento** [comment]
please 🙇

**Comment by nickskull** [comment]
Is the whole iOS team at Facebook on holiday? 😅 Just merge this in please, there's many of us depending on this. 😇

**Comment by poudro** [comment]
Pretty please!

**Comment by vysotsky** [comment]
Any updates?

**Comment by overlordnyaldee** [comment]
Hey everyone, we're aware of this and we're been working to move up our release to push a fix. 

SDK release v4.21 has been pushed yesterday and the issue with conflicting modulemap files should be fixed now. Is anyone still experiencing this issue with this new release?

**Comment by Alak** [comment]
@overlordnyaldee I'll try today :)

**Comment by PSTDev** [comment]
@overlordnyaldee facebook-sdk-swift dependent on this SDK still doesn't compile :(
facebook/facebook-sdk-swift#142

Is Facebook's swift wrapper for this Facebook iOS SDK dead? And should we use only this Objective-C SDK?

**Comment by mcfedr** [comment]
I'd say this issue is fixed.

**Comment by rafcabezas** [comment]
This branch compiles on xcode 8.3.1 via carthage, whereas master doesn't. I still think this PR should be merged in.

**Comment by rafcabezas** [comment]
This branch/PR also works on xcode 8.3.2

**Comment by Infinity-James** [comment]
Not working for me.
I need to use Xcode 8.3 now too because my devices aren't supported.

This is pretty pathetic at this point.

**Comment by adomanico** [comment]
@overlordnyaldee 4.22 still does not compile. Can we merge this?

**Comment by meekay** [comment]
Update after retest. 4.21 succeeds, but 4.22 fails. Looks like there was a regression.
Please provide an update.

**Comment by rafcabezas** [comment]
@overlordnyaldee 4.22 still has the module map issue; please merge this PR in

**Comment by Infinity-James** [comment]
What
Is
Wrong
With
You
?

**Comment by adomanico** [comment]
4.23 still has the module map issue fyi

**Comment by ekimia** [comment]
oh facebook.

**Comment by Infinity-James** [comment]
This is why it sucks to be reliant on anything.

**Comment by mcfedr** [comment]
Yea, contrary to my previous comment, Its not working. Sticking to 4.21 at the moment.

**Comment by dzhuowen** [comment]
Hey everyone,
Please file a bug to https://developers.facebook.com/bugs/ with error description and sample project. We'll work on this issue once we get a valid repo.

**Comment by prsolucoes** [comment]
We need it.

**Comment by prsolucoes** [comment]
I solved it using:

> carthage update --platform iOS

**Comment by mcfedr** [comment]
Reported this bug as https://developers.facebook.com/bugs/1510311509043400/

**Comment by mcohnen** [comment]
Really sorry for the delay here. 
The bug this PR was fixing was already fixed in v4.21: https://github.com/facebook/facebook-ios-sdk/commit/89814273b976cee60e225c3d310cc7075f976ad5
We use xcconfig files instead of modifying project files directly.

There is however a different bug introduced later in v4.22 that is making the build fail in Carthage. This will be fixed in v4.25, which we are aiming to release in July 26th. 
The bug is being tracked here: https://developers.facebook.com/bugs/1510311509043400/

We will include Carthage in our automatic tests to prevent any other breakage in the future.

**Comment by adomanico** [comment]
Thanks @mcohnen

**Comment by mcohnen** [comment]
Quick update: v4.25 is out and Carthage should build now fine.

**Comment by prsolucoes** [comment]
I still have problems with v.4.25 and im backing to 4.21 to compile again.

Error:

```
Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.


Caught signal triggered by the Swift runtime!
Illegal instruction

Unfortunately, this is probably a bug in Swift and not Carthage. If
this is preventing you from doing work, please file an issue and we'll
do our best to work around it:
https://github.com/Carthage/Carthage/issues/new

Please also consider filing a radar with Apple, containing the version
of Carthage and any crash report found in Console.app.

make: *** [carthage-update] Segmentation fault: 11
```

**Comment by mcfedr** [comment]
I am also seeing this issue. But inconsistently, I made a new folder, and Cartfile with just `github "facebook/facebook-ios-sdk" ~> 4.21` and it once loaded fine, and then later didnt work. In my project with other deps, it hasnt worked at all. 

```
Caught signal triggered by the Swift runtime!
Illegal instruction: 4
```

**Pull request closed without merging**
