### PR TITLE
Make FBSDKDynamicFrameworkLoader compile with ARC

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Comment by kastiglione** [comment]
@kolinkrewinkel @indragie plz merge

maxresdefault

**Comment by kastiglione** [comment]
@indragiek @kolinkrewinkel please create a task for this and mark it ubn k thx

**Comment by keith** [comment]
@codytwinton thanks, resolved!

**Comment by keith** [comment]
Thanks!

**Comment by thii** [comment]
Is there any reason why this change was reverted?

**Comment by keith** [comment]
It was reverted??

**Comment by thii** [comment]
Looks like it was reverted before a release, and was never being roll-forwarded then (based on the current revision I just checked on the master branch).

https://github.com/facebook/facebook-objc-sdk/commit/1436a13fbfb8a9cba5f56b29aaab824a637a9706

**Comment by kastiglione** [comment]
Maybe bad merge?

**Pull request merged**
