### PR TITLE
Xcode 8.3 support and added missing framework dependency

### PR DESCRIPTION
**Pull request by arturgrigor**
# Changes
- Added the missing framework to the `FBSDKShareKit_TV-Dynamic` target.
- Fixed the compilation on Xcode 8.3 by renaming the module map files because of this Xcode issue https://openradar.appspot.com/30194818.

`facebook-sdk-swift 0.2.0` doesn't build using Carthage for the tvOS platform because the `CoreGraphics.framework` is missing from `FBSDKShareKit_TV-Dynamic` target.

Issue: https://github.com/facebook/facebook-sdk-swift/issues/120

*Note*: Please note that the [Cartfile](https://github.com/facebook/facebook-sdk-swift/blob/master/Cartfile) from the [facebook-sdk-swift](https://github.com/facebook/facebook-sdk-swift) repo needs to be updated after accepting this PR.

### CODE REVIEW

**Comment by riegerad** [comment]
Is there anything we need to do other than change the project.pbxproj and update to the most recent cart file?

**Comment by refaelte** [comment]
no

2017-04-06 0:20 GMT+03:00 riegerad <notifications@github.com>:

**Comment by riegerad** [comment]
I've done everything but running Carthage update still fails

*** Building scheme "FBSDKShareKit_TV-Dynamic" in FacebookSDK.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/XXX/Documents/XXX/Carthage/Checkouts/facebook-ios-sdk/FacebookSDK.xcworkspace -scheme FBSDKShareKit_TV-Dynamic -configuration Release -derivedDataPath /Users/XXX/Library/Caches/org.carthage.CarthageKit/DerivedData/facebook-ios-sdk/sdk-version-4.21.0 -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/2z/s44s8sps2tg9wdzkl60h864m0000gn/T/carthage-xcodebuild.6lgQsa.log

**Comment by arturgrigor** [comment]
That's all it needed to compile with Xcode 8.2.1. The newest version of Xcode seems to need additional changes.

**Comment by arturgrigor** [comment]
@riegerad I've pushed another commit. You should check now to see if it works for you.

**Comment by riegerad** [comment]
Will running "Carthage update" change all the new stuff you have added? Everything compiles in Xcode its just running the Carthage command the gives me errors. It won't make it through the installation that way so I'm still lacking the actual .framework files.

**Comment by arturgrigor** [comment]
@riegerad it seems that Carthage support needs some more tweaking in order to work with Xcode 8.3 and I don't really have the time at this moment. I will close this PR for now.

**Comment by meekay** [comment]
Guess I don't have time to support Facebook for my users so I'll just switch to Google+ for now.

**Comment by arturgrigor** [comment]
@meekay sorry mate, I'm not an official contributor to this repo, I just tried to help with this PR when Xcode 8.2.1 was out there, but after Xcode 8.3 arrived it messed up the project and I really don't have the time for it, but I'm sure someone else from this community will fix it.

**Comment by meekay** [comment]
Yeah, I deleted my snark when I realized you weren't one of the Facebook folks.

Would appreciate seeing some more support from them on this issue, since at this point I'm seriously wondering why bother.

**Pull request closed without merging**
