### PR TITLE
Fixed NSData is no image

### PR DESCRIPTION
**Pull request by SBrockmann**
If you get an OAuth error so the image is empty.

### CODE REVIEW

**Comment by dzhuowen** [comment]
Hi, can you provide a concrete example of the error? The image is not supposed to be empty.

**Comment by TSBrockmann** [comment]
The easys way to readjust the error is removing the permission from the accesstoken. 
```objective-c
[[[FBSDKGraphRequest alloc] initWithGraphPath:@"me/permissions"
                                       parameters:nil
                                       HTTPMethod:@"DELETE"]
     startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection, id result, NSError *error) {}];
```

**Comment by dzhuowen** [comment]
Can you refactor the change to have only one set of bracket? I'll merge it then.

**Comment by TSBrockmann** [comment]
Okay I've changed it.

**Comment by dzhuowen** [comment]
Hi @TSBrockmann , I cannot repro the error according to your description. Can you provide a sample project with the error? Thanks!

**Comment by TSBrockmann** [comment]
Okay next week i will provide a sample app.

**Comment by TSBrockmann** [comment]
I have upload a sample project. Checkout this [repository](https://github.com/TSBrockmann/FacebookImageViewExample)

**Comment by dzhuowen** [comment]
Fixed in v4.14.0

**Pull request closed without merging**
