### PR TITLE
Xcode10 build fix when using carthage

### PR DESCRIPTION
**Pull request by Nonnus**
Thanks for proposing a pull request.

To help us review the request, please complete the following:

- [x] sign [contributor license agreement](https://developers.facebook.com/opensource/cla)
- [x] submit against our `dev` branch, not `master`.
- [x] describe the change (for example, what happens before the change, and after the change)

This pr fixes compiling with latest xcode 10 using carthage by implementing the fixes described in https://github.com/facebook/facebook-sdk-swift/issues/246

### CODE REVIEW

**Comment by vitorhugomagalhaes** [comment]
Any update on this please ?

**Comment by Nonnus** [comment]
i created the pr, now was waiting for someone to review it...

**Comment by vitorhugomagalhaes** [comment]
I'll use your fork to move forward. Thanks

**Comment by Nonnus** [comment]
@vitorhugomagalhaes keep in mind i also had to patch `Bolts` (https://github.com/BoltsFramework/Bolts-ObjC/pull/323)

in the end to be able to keep working on xcode 10 i ended up making 3 forks and just set my cartfile to point to `github "hellofresh/Facebook-SDK-Swift"`, feel free to use it as well ;)

**Comment by vitorhugomagalhaes** [comment]
Great. Thanks for sharing.

**Comment by vitorhugomagalhaes** [comment]
Any update here ?

**Comment by codytwinton** [comment]
Thank you for this PR! I'll import these changes internally and get it shipped asap.

**Comment by Nonnus** [comment]
@codytwinton my pleasure, happy I could help ;)

**Comment by vitorhugomagalhaes** [comment]
@Nonnus Did you confirmed that the dynamic Bolts framework was being generated on your PR. The hello fresh clone seems to be missing that and then the app will not be able to load it at runtime as required by the other FBSDK frameworks which do rely on the dynamic version of Bolts.

**Comment by codytwinton** [comment]
Still waiting on the PR in Bolts to be merged.

**Pull request closed without merging**
